### ISSUE TITLE
[Feature] Fish support

### ISSUE THREAD

**Issue by MonkeyAndres** [x-cmd/x-cmd#17]
First of all thanks for the work you've been putting into x-cmd. I just installed it in a `toolbox` and it's working great so far.

I'd like to ask for native fish support. I don't know how hard it is to implement this but I'm a fish user and I'd like to have native access to x-cmd and all those amazing tools you're integrating.

**Comment by edwinjhlee** [comment]
Thanks for your credits on x-cmd.

x-cmd have two faces:
- as an exe: download and utilize pkgs in user space. Also shell application module ( LLM/Cloud cli ... )
- as a library for posix shell


In the near future, I will add a shell wrapper support in fish/powershell/csh/... any other non-posix shell. 
In that way, fish/csh/powrshell user can utilize x-cmd pkg system and application module.


In the future, I might write a special version for fish by converting the posix code to fish code, once the x-cmd core is stable. 


We will notify you in this issue once fish support is ready.

**Comment by edwinjhlee** [comment]
In the next version of x-cmd(v0.3.10), I will add some beta support for fish user.

```bash
x fish --setup  # fish user will have to invoke it first, so fishrc will activate x-cmd during setup.
```

Then the fish user can invoke x-cmd as a binary.

```fish
x <..., like jq, yq, ollama, hn, ...>
```

Notice, the environment variable cannot be passed to the fish shell, so some of the nice features in x-cmd cannot work on that version.
And the startup latency of invoking x will also be a issue (20ms-50ms for each invoke). But it can be optimized.

But at least all of the pkg and application modules can be invoked in that way.



Fish is a very interesting language. But before I knew fish, I had already been familiar with bash. We don't have a dedicate fish user in our dev team. In the recent years I always thinking of what shoud we do if hypothetically x-cmd run in fish/csh or any other non-posix shell. 

I do have some ideas about that. We have a fish module ( just like python module ) in our inner dev version. But because I don't have a user -- Er... as you can see, x-cmd doest get a lot of attention -- that's why we don't release our limited work on fish in the public version.

If you are interested in it, welcome to be our first user on fish module in the next version.

**Comment by edwinjhlee** [comment]
We now can run `x ollama` and `x tldr` in fish/csh using x-cmd's dev version.

You can also run `x env use` or `x <pkg, like jq, yq>`. Basically, you can use 'x env use' for almost all packages provided by x-cmd.


This dev version will release as v0.3.10 in two days.


The problem is since we cannot pass the environement variables to fish shell, the application's modification on environment variables cannot take effect. For example, our 'c' command requires modifing the variable of 'current work directory'. [cd](http://www.x-cmd.com/mod/cd)

This requires a general consideration. It might take a while, maybe 1-2 months.

**Comment by edwinjhlee** [comment]
You can check out v0.3.10 and have a try.

**Comment by Zhengqbbb** [comment]
**ref:**
- https://www.x-cmd.com/v/0.3.10/#csh-fish-nu-onsh
- https://www.x-cmd.com/blog/240611#%E2%9C%A8-csh-fish-nu-onsh-modules
- https://www.x-cmd.com/blog/240610#_5-non-posix-shells-nushell-fish-xonsh-csh-pwsh
